[build]
  command = "npm install && npm run build"
  publish = "dist/spa"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_RESOLVE_EXTENSIONS = ".js,.json,.vue"
